// Generated by CoffeeScript 1.6.3
(function() {
  var checkComplete, checkCompleteInterval, lastReceived, page, requestCount, requestIds, responseCount, system,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  page = require('webpage').create();

  system = require('system');

  lastReceived = new Date().getTime();

  requestCount = 0;

  responseCount = 0;

  requestIds = [];

  page.viewportSize = {
    width: 1024,
    height: 768
  };

  page.onResourceReceived = function(response) {
    var requestIdx;
    requestIdx = requestIds.indexOf(response.id);
    if (requestIdx !== -1) {
      lastReceived = new Date().getTime();
      responseCount++;
      return requestIds[requestIdx] = null;
    }
  };

  page.onResourceRequested = function(request) {
    var _ref;
    if (_ref = request.id, __indexOf.call(requestIds, _ref) < 0) {
      requestIds.push(request.id);
      return requestCount++;
    }
  };

  page.open(system.args[1], (function() {}));

  checkComplete = function() {
    if (!(new Date().getTime() - lastReceived > 300 && requestCount === responseCount)) {
      return;
    }
    clearInterval(checkCompleteInterval);
    console.log(page.content);
    return phantom.exit();
  };

  checkCompleteInterval = setInterval(checkComplete, 1);

}).call(this);
